root: true
env:
  browser: true
  es2022: true
extends:
  - htmlacademy/vanilla

parserOptions:
  ecmaVersion: latest
  sourceType: module


globals:
  noUiSlider: readonly
  Pristine: readonly
# здесь можно переписать правила, которые не нравятся. Например сделать нормальные отступы 
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1